name: test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: ${{ matrix.lisp }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        lisp:
        - clasp
        - ecl
        - sbcl
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yitzchak/archlinux-cl:latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: yitzchak/ansi-test-harness
        path: ansi-test-harness
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: anatomicl
    - name: Setup Lisp Environment
      run: |
        make-rc
        asdf-add
    - name: Run ANSI Tests
      run: |
        lisp -i ${{ matrix.lisp }} -e "(ql:quickload :anatomicl-extrinsic/test)" -e "(asdf:test-system :anatomicl-extrinsic)"
